# Generated by Django 3.2.23 on 2023-12-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
        ('checkout', '0004_auto_20231124_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bag.coupon'),
        ),
    ]
