# Generated by Django 3.2.23 on 2023-12-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20231221_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
    ]
