# Generated by Django 3.2.23 on 2023-12-30 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(null=True, verbose_name=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
    ]
